// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type GetTokenResponse struct {
	Success bool    `json:"success"`
	Token   *string `json:"token,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID       int     `json:"id"`
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Token    *string `json:"token,omitempty"`
}
